### ISSUE TITLE
where does ofxRunwayModelUtils.h gone?

### ISSUE THREAD

**Issue by 2bbb** [runwayml/ofxRunway#10]
isn't it necessary?
if so, we need to update all example projects?

**Comment by roymacdonald** [comment]
Hi, 
I took it away because there was no need for it, as I ended up not needing any of its functions.
I don't see the need to update all examples except for updating the xcode project, which Project Generator can do quite easily.
This addon is still a work in progress. So if you see anything that could be improved I would really appreciate your insight. :)

**Comment by 2bbb** [comment]
Hi.
I know what we can build it and update is easy with pg.

but when I teach for beginners using this addon, some beginners say "this source is not there. It is ok?"
so, i think, if it is easy to fix then shouldn't fix it?

of course, if you think to don't fix is correct way of this addon, i say nothing.

**Comment by roymacdonald** [comment]
Sure I understand you. 
I'll fix it now. My apologies if this confused your students.
As well, I'd be glad if you would let me know how is that you teach your students to use OF+runway. In the sense of "Which are the scenarios in which using both is needed, instead of doing it right in the RunwayML GUI ?". As well, you can join the [public slack channel](https://runwayml.com/joinslack) to share your thoughts, insight and vision with others using runway and the runway team.

**Comment by 2bbb** [comment]
@roymacdonald 
Thanks for updating quickly!!
I tell my students to updating!

so, "why we use oF+runway" is what we want to use ML results data for visualizing with oF (maybe some students want to use realtime).
I wrote the json parser for some models in runwayml, but so many models is in runway...
and ofxRunway is awesome because corresponds many models.

**Comment by roymacdonald** [comment]
No problem. Please let me know in case you find anything else.
Glad to know that ofxRunway works for you. :)
My intention is to cover all the available models. I'll keep on updating.
best
