### ISSUE TITLE
connecting to different models for input vs output

### ISSUE THREAD

**Issue by digitalcoleman** [runwayml/ofxRunway#12]
I am trying to send a vector to one model and then get a returned image out of a second model, having those two models linked inside runway. There seems to be an issue getting that returned image. I assume I need to use two instances of ofxRunway, each with a different host number. I am getting the debug info from the second runway instance rather than the actual data. Has this been tested or are there any leads to making this work?

**Comment by roymacdonald** [comment]
Hi Chris, I never tested that! 
Although, from how this addon and the runway API works I am not sure if it is possible to have a setting as you described.
Currently, when you send something there is an http request made to runway, which runs on another thread and it just waits until it gets a response back from runway with the results.

The setting you are using is tricky for how it works now, as there is no request made to the second model it will never be waiting for a response. As well I think that it is not even how http works. 
Easy fix, don't connect the models through runway. Simply have 2 ofxRunway instances, one connected to each model, and when the first gets a response send it immediately to the second. I could guess that there shouldn't be such a big overhead on such operation, because it is more or less the same as runway does internally when linking models, considering that each model runs remotely on a different virtual machine. Good part of this, you can add an extra step of processing, if needed, between receiving from the first and sending to the second.

I am not sure how to properly fix this, I would need to discuss it with the rest of the team as I do not have enough insight on the inner workings of runway and how it notifies. Maybe using the Socket.io implementation you could wait for the second model to notify. 

@cvalenzuela @brannondorsey @agermanidis how would you do this? (in general terms, not OF or C++, simply how would you handle this send and receive scenario)

**Comment by digitalcoleman** [comment]
Ok, thanks! I did manage to make an example that shows how you can talk to each model, bring the result to OF and then send it back out to the next model. Others can find it here if needed: [Multi-Model Example](https://bitbucket.org/professorColeman/multi-model_example/src/master/)

**Comment by roymacdonald** [comment]
Hi @digitalcoleman Thanks! I'll take a look at it tomorrow.
